#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'isPalindrome' function below.
#
# The function is expected to return a BOOLEAN.
# The function accepts STRING s as parameter.
#

def isPalindrome(s):
    s = s.lower();
    # Write your code here
    if(len(s) <= 1):
        return True;
    elif(s == s[::-1]):
        return True;
    return False;

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = isPalindrome(s)

    fptr.write(str(int(result)) + '\n')

    fptr.close()
